version: '3'
services:
   postgres:
    image: postgres:10.3
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./dev-data/postgres:/var/lib/postgresql/data
    ports:
      - 15432:5432
