name:                typed-admin
version:             0.1.0.0
github:              "nakaji-dayo/typed-admin"
license:             BSD3
author:              "Daishi Nakajima"
maintainer:          "nakaji.dayo@gmail.com"
copyright:           "2018 Daishi Nakajima"

extra-source-files:
- README.md
- ChangeLog.md
- templates/javascript/*.js

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/nakaji-dayo/typed-admin#readme>

dependencies:
- base >= 4.7 && < 5
- wai
- warp
- wai-extra
- relational-record
- relational-query
- relational-query-HDBC
- persistable-record
- HDBC
- HDBC-postgresql
- HDBC-session
- template-haskell
- http-types
- lucid
- text
- utf8-string
- bytestring
- transformers
- mtl
- exceptions
- generic-lens >= 1.1.0.0
- time
- data-default-class
- http-api-data
- yaml
- unordered-containers
- monad-control
- transformers-base
- blaze-markup
- heterocephalus

library:
  source-dirs: src

executables:
  typed-admin-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - typed-admin
    - lens
    - generic-lens >= 1.1.0.0
    when:
    - condition: ! '!(flag(example))'
      buildable: false

# tests:
#   typed-admin-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - typed-admin

flags:
  example:
    description: build example
    manual: true
    default: false
